name: cffconvert
on:
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  validate:
    name: validate
    runs-on: monkci-ubuntu-24.04-4
    steps:
    - name: Check out a copy of the repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
    - name: Check whether the citation metadata from CITATION.cff is valid
      uses: citation-file-format/cffconvert-github-action@4cf11baa70a673bfdf9dad0acc7ee33b3f4b6084
      with:
        args: --validate
