name: CI
on:
  workflow_dispatch: {}
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.ref != 'master' }}
jobs:
  build-linux-x86-cpu:
    uses: ./.github/workflows/build-reusable.yml
    with:
      runner: linux-x86-n2-16
      tfci: py313,linux_x86,rbe,no_docker
    if: ${{ false }}
  build-linux-x86-cuda:
    uses: ./.github/workflows/build-reusable.yml
    with:
      runner: linux-x86-n2-16
      tfci: py313,linux_x86_cuda,rbe,no_docker
    if: ${{ false }}
  build-linux-x86-cuda13:
    uses: ./.github/workflows/build-reusable.yml
    with:
      runner: linux-x86-n2-16
      tfci: py313,linux_x86_cuda13_nvcc,rbe,no_docker
    if: ${{ false }}
  build-arm64:
    uses: ./.github/workflows/build-reusable.yml
    with:
      runner: linux-x86-n2-16
      tfci: py313,linux_arm64_cross_compile,rbe,no_docker,enable_pycpp_build
      job_name: build-only
    if: ${{ false }}
  build-windows-x86:
    uses: ./.github/workflows/build-reusable.yml
    with:
      runner: windows-x86-n2-16
      tfci: py313,windows_x86_ml_actions,rbe
    if: ${{ false }}
