name: Creates a GitHub Issue when a PR Rolled back via Commit to Master
on:
  workflow_dispatch: {}
permissions: {}
jobs:
  create-issue-on-pr-rollback:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: read
    if: 'github.repository == ''tensorflow/tensorflow'' &&

      startsWith(github.event.head_commit.message, ''Rollback of PR #'')

      '
    steps:
    - name: Checkout repo
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
    - name: Create a new Github Issue
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: 'const script = require(''./.github/workflows/create_issue.js'')

          console.log(await script({github, context}))

          '
