name: OSV-Scanner Scheduled Scan
on:
  workflow_dispatch: {}
permissions:
  security-events: write
  contents: read
jobs:
  scan-scheduled:
    if: ${{ false }}
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v2.3.1
    with:
      scan-args: '--lockfile=requirements.txt:./requirements_lock_3_9.txt

        --lockfile=requirements.txt:./requirements_lock_3_10.txt

        --lockfile=requirements.txt:./requirements_lock_3_11.txt

        --lockfile=requirements.txt:./requirements_lock_3_12.txt

        --lockfile=requirements.txt:./ci/official/containers/linux_arm64/devel.requirements.txt

        --lockfile=requirements.txt:./ci/official/containers/linux_arm64/jax.requirements.txt

        --lockfile=requirements.txt:./ci/official/containers/linux_arm64/devel.usertools/test.requirements.txt'
